.TH CASTDISP 1 "October 2026" "1.0.0" "castdisp Manual"
.SH NAME
castdisp \- Universal Linux Display and Audio Projector Layout Switcher
.SH SYNOPSIS
.B castdisp
[I--modeR {IinternalR|ImirrorR|IextendR|IexternalR}]
.SH DESCRIPTION
.B castdisp
is a native desktop widget overlay designed to reproduce the Windows 'Super+P' display layout cycling behavior inside Linux environments.